/* =====================================================================
   ordlister.js - ordene i Syregalgen

   Hver liste er tekst, én linje pr. ord:

     ORD ; ledetråd ; forklaring

   * ORD skrives med store bogstaver. Kun A til Å, mellemrum og
     bindestreg. Mellemrum og bindestreg vises fra starten.
   * Ledetråden er en kort definition, der ikke nævner ordet. Den koster
     et skridt mod karret at se.
   * Forklaringen vises, når ordet er gættet eller tabt.
   * "Område id: Navn" begynder et nyt træningsområde. "//" er en kommentar.
   * Semikolon må ikke bruges inde i teksterne.

   Selvtesten (_selvtest.html) tjekker formatet, at ingen ledetråd nævner
   sit eget ord, og at intet ord står to gange.
   ===================================================================== */
(function () {
    "use strict";

    var NK = window.NK;

    var KEMI = [
        "Område c1: C1 Atomer",
        "ATOMKERNE ; Den lille, tunge midte af et atom med protoner og neutroner. ; Atomkernen rummer næsten hele atomets masse, men kun en forsvindende lille del af dets rumfang.",
        "PROTON ; Positivt ladet partikel i atomkernen. ; Antallet af protoner er lig med atomnummeret og bestemmer, hvilket grundstof atomet er.",
        "NEUTRON ; Partikel i atomkernen uden ladning. ; Neutroner vejer næsten det samme som protoner. Antallet kan variere mellem atomer af samme grundstof.",
        "ELEKTRON ; Lille, negativt ladet partikel, der bevæger sig uden om kernen. ; En elektron vejer ca. 1/1800 af en proton. Et neutralt atom har lige mange elektroner og protoner.",
        "NUKLEON ; Fællesnavn for protoner og neutroner. ; Antallet af nukleoner i kernen kaldes massetallet.",
        "ATOMNUMMER ; Antallet af protoner i kernen. ; Atomnummeret bestemmer grundstoffet. Carbon har nr. 6, fordi det har 6 protoner.",
        "MASSETAL ; Antallet af protoner og neutroner i kernen tilsammen. ; Carbon-14 har 14 nukleoner: 6 protoner og 8 neutroner.",
        "ISOTOP ; Atomer af samme grundstof med forskelligt antal neutroner. ; Carbon-12 og carbon-14 er isotoper. Begge har 6 protoner, men 6 og 8 neutroner.",
        "ELEKTRONSKAL ; Et af de lag uden om kernen, som de negative partikler er fordelt i. ; Den inderste kan rumme 2 elektroner og den næste 8.",
        "VALENSELEKTRON ; En elektron i atomets yderste skal. ; Valenselektronerne indgår i kemiske bindinger. Chlor har 7, fordi det står i 7. hovedgruppe.",
        "ELEKTRONFORDELING ; Tal som 2, 8, 1, der viser, hvor mange der sidder i hver skal. ; Natrium har elektronfordelingen 2, 8, 1. Den sidste elektron afgiver det let.",
        "OKTETREGLEN ; Atomer får gerne otte elektroner i yderste skal. ; Derfor afgiver natrium én elektron, og chlor optager én. Hydrogen og helium nøjes med to.",
        "ION ; Atom eller atomgruppe med elektrisk ladning. ; En ion dannes, når et atom afgiver eller optager elektroner. Na⁺ har afgivet én, Cl⁻ har optaget én.",
        "PERIODESYSTEMET ; Skemaet, hvor alle grundstoffer står ordnet efter atomnummer. ; Rækkerne kaldes perioder og søjlerne grupper. Grundstoffer i samme hovedgruppe ligner hinanden kemisk.",
        "HOVEDGRUPPE ; Lodret søjle i det periodiske system, fx den med alkalimetallerne. ; Grundstoffer i samme hovedgruppe har lige mange valenselektroner og ligner derfor hinanden kemisk.",
        "PERIODE ; Vandret række i skemaet over alle grundstoffer. ; Periodens nummer er antallet af elektronskaller, atomerne bruger.",
        "GRUNDSTOF ; Stof, der kun består af én slags atomer. ; Der kendes 118 af dem. Hvert har sit eget symbol, fx Fe for jern.",
        "METAL ; Grundstof, der leder strøm og varme og står til venstre og i midten af det periodiske system. ; Metaller afgiver elektroner og danner positive ioner. Omkring tre fjerdedele af grundstofferne er metaller.",
        "IKKE-METAL ; Grundstof øverst til højre i det periodiske system, fx oxygen eller svovl. ; Ikke-metaller optager eller deler elektroner og danner negative ioner eller molekyler.",
        "ÆDELGAS ; Grundstof i sidste hovedgruppe, der næsten aldrig reagerer. ; Ædelgasserne har fuld yderste skal. Helium, neon og argon er eksempler.",
        "ALKALIMETAL ; Blødt, meget reaktivt metal i 1. hovedgruppe. ; Alkalimetallerne har én valenselektron, som de let afgiver. Natrium og kalium reagerer voldsomt med vand.",
        "JORDALKALIMETAL ; Metal i 2. hovedgruppe, fx magnesium eller calcium. ; De har to valenselektroner og danner ioner som Mg²⁺ og Ca²⁺.",
        "HALOGEN ; Grundstof i 7. hovedgruppe, fx chlor eller brom. ; Halogenerne har syv valenselektroner og optager let én elektron, så de danner ioner som Cl⁻.",
        "HYDROGEN ; Grundstof nr. 1 og det letteste af alle. ; Hydrogen findes som H₂ og brænder med et knald sammen med oxygen.",
        "HELIUM ; Grundstof nr. 2. Gassen i balloner, der stiger til vejrs. ; Helium er lettere end luft og reagerer ikke med noget.",
        "CARBON ; Grundstof nr. 6. Findes i alle organiske stoffer. ; Diamant og grafit er begge rent carbon. Symbolet er C.",
        "NITROGEN ; Grundstof nr. 7. Udgør ca. 78 % af luften. ; Nitrogen findes som N₂ med en tripelbinding og er meget lidt reaktivt.",
        "OXYGEN ; Grundstof nr. 8. Udgør ca. 21 % af luften. ; Oxygen findes som O₂ og er nødvendigt for forbrænding. I forbindelser har det oftest oxidationstallet −II.",
        "NATRIUM ; Grundstof nr. 11. Blødt alkalimetal, der også findes i køkkensalt. ; Natrium danner ionen Na⁺. Metallet opbevares i olie, fordi det reagerer med vand og luft.",
        "CHLOR ; Grundstof nr. 17. Grøngul, giftig gas og et halogen. ; Chlor findes som Cl₂ og danner chloridionen Cl⁻, fx i NaCl.",
        "REAKTIONSSKEMA ; Viser en kemisk omdannelse med formler og en pil. ; Til venstre for pilen står reaktanterne, til højre produkterne, fx 2 H₂ + O₂ → 2 H₂O.",
        "REAKTANT ; Stof, der bruges op i en kemisk reaktion. ; Reaktanterne står til venstre for pilen i reaktionsskemaet.",
        "PRODUKT ; Stof, der dannes ved en kemisk reaktion. ; Produkterne står til højre for pilen i reaktionsskemaet.",
        "KOEFFICIENT ; Det store tal foran en formel i et reaktionsskema. ; Koefficienterne afstemmer skemaet. I 2 H₂O er 2 koefficienten.",
        "AFSTEMNING ; At sørge for lige mange atomer af hver slags på begge sider af pilen. ; Man retter kun de store tal foran formlerne, aldrig de små tal inde i dem.",
        "TILSTANDSFORM ; Angives med (s), (l), (g) eller (aq) efter formlen. ; (s) er fast, (l) er flydende, (g) er gas, og (aq) betyder opløst i vand.",
        "EXOTERM ; Om en reaktion, der afgiver energi, så omgivelserne bliver varmere. ; Forbrænding er exoterm, fx CH₄ + 2 O₂ → CO₂ + 2 H₂O.",
        "ENDOTERM ; Om en reaktion, der optager energi, så omgivelserne bliver koldere. ; Opløsning af ammoniumnitrat i vand er endoterm. Det bruges i kuldeposer.",
        "KATALYSATOR ; Stof, der får en reaktion til at gå hurtigere uden selv at blive brugt op. ; Bilens katalysator omdanner CO til CO₂. Enzymer er kroppens egne.",
        "MIKROSKOPISK ; Det niveau, hvor stoffer beskrives som atomer og molekyler. ; Modsætningen er det makroskopiske niveau: det, man kan se og måle i laboratoriet.",
        "MAKROSKOPISK ; Det niveau, man kan se og måle direkte, fx farve og kogepunkt. ; Modsætningen er det mikroskopiske niveau med atomer og molekyler.",

        "Område c2: C2 Ionforbindelser",
        "IONFORBINDELSE ; Stof opbygget af positive og negative ioner. ; De kaldes også salte. De har høje smeltepunkter, fordi ionerne sidder fast i et gitter.",
        "SALT ; Andet ord for en ionforbindelse. ; Køkkensalt er natriumchlorid, NaCl, men kobbersulfat og kalk er også salte.",
        "IONGITTER ; Regelmæssigt, tredimensionelt mønster af positive og negative ioner. ; Ionerne holdes sammen af tiltrækningen mellem modsatte ladninger. I NaCl har hver Na⁺ seks Cl⁻ som naboer.",
        "IONBINDING ; Tiltrækningen mellem positive og negative ioner. ; Den opstår typisk mellem et metal og et ikke-metal, når forskellen i elektronegativitet er over ca. 2.",
        "SAMMENSAT ION ; Ladet partikel af flere atomer, fx NO₃⁻ eller NH₄⁺. ; Atomerne indeni holdes sammen af elektronparbindinger, og ionen har samlet én ladning.",
        "CHLORID ; Navnet på ionen Cl⁻. ; Negative ioner af ét grundstof får endelsen -id: chlorid, oxid, sulfid.",
        "OXID ; Navnet på ionen O²⁻. ; Magnesiumoxid, MgO, og calciumoxid, CaO, er ionforbindelser med denne ion.",
        "SULFAT ; Navnet på den sammensatte ion SO₄²⁻. ; Kobbersulfat, CuSO₄, er et blåt salt med krystalvand.",
        "NITRAT ; Navnet på den sammensatte ion NO₃⁻. ; Alle salte med denne ion er letopløselige. Sølvnitrat bruges til at påvise chloridioner.",
        "CARBONAT ; Navnet på den sammensatte ion CO₃²⁻. ; Kalk er calciumcarbonat, CaCO₃. Hælder man syre på, bruser det af CO₂.",
        "HYDROXID ; Navnet på ionen OH⁻. ; Natriumhydroxid, NaOH, er en stærk base.",
        "AMMONIUM ; Navnet på den sammensatte ion NH₄⁺. ; Den er en af de få positive sammensatte ioner. Salmiak er ammoniumchlorid.",
        "OPLØSNING ; Blanding, hvor et stof er fordelt helt jævnt i et andet, fx salt i vand. ; Vandet kaldes opløsningsmidlet, og saltet kaldes det opløste stof.",
        "OPLØSELIGHED ; Hvor mange gram af et stof, 100 mL vand højst kan tage op. ; Den afhænger af temperaturen og angives fx i gram pr. 100 mL vand.",
        "LETOPLØSELIG ; Om et salt, hvor mindst 1 g kan opløses i 100 mL vand ved 20 °C. ; I tabellen står der L. Natriumchlorid og alle nitrater er eksempler.",
        "TUNGTOPLØSELIG ; Om et salt, hvor under 1 g kan opløses i 100 mL vand ved 20 °C. ; I tabellen står der T. Sølvchlorid og calciumcarbonat er eksempler.",
        "FÆLDNINGSREAKTION ; To klare opløsninger blandes, og et fast stof dannes. ; Fx Ag⁺(aq) + Cl⁻(aq) → AgCl(s). Det faste stof er tungtopløseligt.",
        "BUNDFALD ; Det faste stof, der dannes, når to opløsninger blandes. ; Det er et tungtopløseligt salt og skrives med (s) i reaktionsskemaet.",
        "TILSKUERION ; Ion, der er i opløsningen, men ikke deltager i reaktionen. ; Blandes NaCl og AgNO₃, fældes AgCl, mens Na⁺ og NO₃⁻ bare er til stede.",
        "SØLVCHLORID ; Det hvide bundfald, der viser, at en opløsning indeholder Cl⁻. ; AgCl dannes, når sølvnitrat tilsættes. Det bliver gråt i sollys.",
        "KRYSTALVAND ; Vandmolekyler, der sidder fast inde i visse faste salte, fx blå vitriol. ; Blå vitriol er CuSO₄·5H₂O. Opvarmes det, forsvinder vandet, og saltet bliver hvidt.",
        "TRIVIALNAVN ; Hverdagsnavn for et stof, fx salmiak eller kalk. ; Det systematiske navn for salmiak er ammoniumchlorid.",
        "SYSTEMATISK NAVN ; Betegnelse efter faste regler, fx natriumchlorid for køkkensalt. ; Den positive ion nævnes først, den negative sidst.",

        "Område c3: C3 Molekyler",
        "MOLEKYLE ; Gruppe af atomer, der holdes sammen af elektronparbindinger. ; Vand, H₂O, er et molekyle af tre atomer.",
        "KOVALENT BINDING ; Når to atomer deler et elektronpar. ; Den kaldes også elektronparbinding og findes mellem ikke-metalatomer, fx i H₂, H₂O og CH₄.",
        "ELEKTRONPARBINDING ; Andet ord for en kovalent binding. ; To atomer deler et elektronpar. Den tegnes som en streg i en strukturformel.",
        "DOBBELTBINDING ; To elektronpar, der deles mellem de samme to atomer. ; Den findes fx i O₂ og mellem C-atomerne i ethen, C₂H₄.",
        "TRIPELBINDING ; Tre elektronpar, der deles mellem de samme to atomer. ; Nitrogen, N₂, holdes sammen af en af dem og er derfor meget stabilt.",
        "ELEKTRONPRIKFORMEL ; Tegning af et molekyle, hvor bindende par er streger og ledige par er prikker. ; Bindende elektronpar tegnes som streger mellem atomerne og ledige par som prikker.",
        "LEDIGT ELEKTRONPAR ; To prikker på et atom, der ikke indgår i en binding. Vand har to par på O. ; Oxygen i vand har to af dem. De skubber til bindingerne og giver den vinklede form.",
        "MOLEKYLFORMEL ; Viser, hvilke og hvor mange atomer stoffet består af, fx C₂H₆O. ; Den viser ikke, hvordan atomerne sidder. Ethanol og dimethylether har samme.",
        "STRUKTURFORMEL ; Tegning, der viser, hvordan atomerne i et molekyle er bundet til hinanden. ; Bindingerne tegnes som streger. Den viser forskellen på isomerer med samme molekylformel.",
        "CENTRALATOM ; Atomet i midten, som de andre atomer i molekylet er bundet til. ; I CH₄ er det carbon. Formen afhænger af, hvor mange elektronpar der sidder om det.",
        "ELEKTRONEGATIVITET ; Et mål for, hvor kraftigt et atom trækker i bindingsparret. Fluor har den højeste. ; Fluor har den højeste værdi, 4,0. Forskellen afgør, om en binding er upolær, polær eller en ionbinding.",
        "POLÆR ; Om en binding, hvor elektronerne er skævt fordelt mellem to atomer. ; Et molekyle er polært, når de skæve bindinger ikke udligner hinanden, fx H₂O. CO₂ er upolært.",
        "UPOLÆR ; Om et molekyle uden positiv og negativ ende, fx CH₄ eller O₂. ; Upolære stoffer blandes godt med hinanden, men dårligt med vand.",
        "DIPOL ; Molekyle med en positiv og en negativ ende. ; Vand er en dipol, fordi oxygen trækker mere i elektronerne end hydrogen.",
        "TETRAEDER ; Rumlig form, hvor fire atomer sidder om et centralatom med vinkler på ca. 109,5°. ; Methan, CH₄, har den form.",
        "VINKLET ; Formen på et vandmolekyle. ; H₂O har den form, fordi de to ledige elektronpar på oxygen skubber til bindingerne.",
        "LINEÆR ; Formen på CO₂, hvor alle tre atomer ligger på en ret linje. ; Bindingsvinklen er 180°.",
        "BINDINGSVINKEL ; Er ca. 109,5° i methan og ca. 104,5° i vand. ; Det er vinklen mellem to bindinger fra samme atom. De ledige elektronpar i vand presser den ned.",
        "HYDROGENBINDING ; Stærk tiltrækning mellem et H på N, O eller F og et ledigt elektronpar på et naboatom. ; Den giver vand et højt kogepunkt i forhold til molekylets størrelse.",
        "LONDON-KRÆFTER ; Svag tiltrækning mellem alle molekyler, størst mellem store molekyler. ; De skyldes små, tilfældige skævheder i elektronskyen og er de eneste kræfter mellem upolære molekyler.",
        "INTERMOLEKYLÆR ; Om kræfter, der virker mellem molekylerne, ikke inde i dem. ; Hydrogenbindinger og London-kræfter er eksempler. De bestemmer kogepunktet.",
        "KOGEPUNKT ; Den temperatur, hvor et stof går fra væske til gas. ; Jo stærkere kræfter mellem molekylerne, jo højere er det.",
        "SMELTEPUNKT ; Den temperatur, hvor et stof går fra fast form til væske. ; Salte har høje værdier, fordi ionbindinger er stærke. NaCl smelter ved 801 °C.",
        "BLANDBARHED ; Om to væsker giver én fase eller lægger sig i to lag, når de hældes sammen. ; Lige opløser lige: polære stoffer blandes med polære, upolære med upolære.",
        "FASE ; Et område i en blanding, hvor alt er ens hele vejen igennem. ; Olie og vand giver to. Is og vand er også to.",
        "HYDROFIL ; Vandelskende. ; Polære grupper som -OH er vandelskende. Modsætningen er hydrofob.",
        "HYDROFOB ; Vandskyende. ; Lange carbonhydridkæder er vandskyende. Derfor blandes olie ikke med vand.",

        "Område c4: C4 Beregninger",
        "STOFMÆNGDE ; Antallet af partikler talt i mol. Symbolet er n. ; Den beregnes ofte som n = m / M.",
        "MOL ; Enheden for stofmængde. ; 1 mol er 6,022 · 10²³ partikler.",
        "MOLARMASSE ; Massen af 1 mol af et stof, målt i g/mol. Symbolet er M. ; Den findes ved at lægge atommasserne sammen. For H₂O er den 2 · 1,008 g/mol + 16,00 g/mol = 18,02 g/mol.",
        "ATOMMASSE ; Et atoms masse, målt i u. Står i det periodiske system. ; Carbon har 12,01 u. Samme tal i g/mol er molarmassen.",
        "AVOGADROS KONSTANT ; Antallet af partikler i 1 mol: 6,022 · 10²³ pr. mol. ; Antal partikler = stofmængde · 6,022 · 10²³ /mol.",
        "MASSE ; Hvor meget et stof vejer, målt i gram. Symbolet er m. ; I kemi regner man oftest med m = n · M.",
        "AFVEJNING ; At måle en bestemt masse af et stof af på en vægt. ; Skal man bruge 0,10 mol NaCl, afvejer man m = 0,10 mol · 58,44 g/mol = 5,8 g.",
        "STØKIOMETRISK FORHOLD ; Tallene fra koefficienterne i et afstemt skema, fx 2 : 1. ; I 2 H₂ + O₂ → 2 H₂O reagerer H₂ og O₂ i forholdet 2 : 1.",
        "ÆKVIVALENTE MÆNGDER ; Så meget af hvert stof, at det passer præcis sammen efter reaktionsskemaet. ; Så bliver ingen af reaktanterne til overs.",
        "BEGRÆNSENDE REAKTANT ; Det stof, der slipper op først, så reaktionen stopper. ; Det bestemmer, hvor meget produkt der dannes. Resten af de andre stoffer er i overskud.",
        "OVERSKUD ; Det, der er tilbage af en reaktant, når den anden er brugt op. ; Tilsætter man mere af et stof end nødvendigt, bliver resten liggende efter reaktionen.",
        "BEREGNINGSSKEMA ; Skema med rækker for M, m og n under reaktionsskemaet. ; Man udfylder det kendte, regner n ud og bruger forholdet mellem koefficienterne til at finde resten.",
        "UDBYTTE ; Hvor meget produkt man faktisk fik, i procent af det, man kunne have fået. ; Det beregnes som faktisk masse / teoretisk masse · 100 %.",
        "IDEALGASLIGNINGEN ; pV = nRT. ; Den forbinder tryk, rumfang, stofmængde og temperatur for en gas.",
        "GASKONSTANTEN ; R i pV = nRT. Værdien er 8,314 J/(mol·K). ; Den er ens for alle gasser, der opfører sig som en idealgas.",
        "TRYK ; Kraft pr. areal. I kemi ofte målt i kPa. ; Symbolet er p. Luftens tryk ved havoverfladen er ca. 101,3 kPa.",
        "KELVIN ; Temperaturskalaen, hvor 0 er det absolutte nulpunkt. ; T = t + 273,15, hvor T er i kelvin og t i °C. Den bruges i pV = nRT.",
        "DET ABSOLUTTE NULPUNKT ; 0 K eller −273,15 °C. ; Den laveste temperatur, der findes. Partiklerne bevæger sig så lidt som muligt.",
        "DENSITET ; Masse pr. rumfang, fx i g/mL. ; Vand har ca. 1,00 g/mL. Massen findes som m = ρ · V.",
        "VOLUMEN ; Hvor meget plads et stof fylder, fx i mL eller L. ; Symbolet er V. 1 L = 1000 mL = 1 dm³.",
        "BETYDENDE CIFRE ; Dem tæller man for at se, hvor præcist et tal er angivet: 2,50 har tre. ; Et resultat angives med lige så mange som det mindst præcise måltal.",
        "FORBRÆNDING ; Reaktion med oxygen, hvor der dannes varme og ofte en flamme. ; Brænder et carbonhydrid helt, dannes CO₂ og H₂O.",

        "Område c5: C5 Koncentration",
        "KONCENTRATION ; Hvor meget stof, der er opløst pr. rumfang opløsning. ; Den måles typisk i mol/L.",
        "STOFMÆNGDEKONCENTRATION ; c = n / V, målt i mol/L. ; Det er stofmængden af opløst stof pr. liter opløsning.",
        "FORMEL KONCENTRATION ; Den, man skriver c(X): det, der blev hældt i, uden hensyn til, hvad stoffet blev til. ; 0,10 M CaCl₂ har c(CaCl₂) = 0,10 M, selv om der ikke er ét eneste CaCl₂ i vandet.",
        "AKTUEL KONCENTRATION ; Den, man skriver [X]: det, opløsningen faktisk indeholder. ; I 0,10 M CaCl₂ er [Ca²⁺] = 0,10 M og [Cl⁻] = 0,20 M.",
        "FORTYNDING ; At tilsætte mere vand, så koncentrationen falder. ; Stofmængden er den samme før og efter: c₁ · V₁ = c₂ · V₂.",
        "OPLØSNINGSMIDDEL ; Det stof, der opløser et andet, oftest vand. ; I en saltopløsning er vand dette stof, og saltet er det opløste stof.",
        "MÆTTET OPLØSNING ; Når vandet ikke kan opløse mere af stoffet. ; Tilsætter man mere, bliver det liggende som fast stof på bunden.",
        "KONCENTRERET ; Om en opløsning med meget stof pr. rumfang, fx syre direkte fra flasken. ; Modsætningen er fortyndet. Hæld altid syre i vand, ikke vand i syre.",
        "MÅLEKOLBE ; Kolbe med en streg på halsen til at lave et nøjagtigt rumfang opløsning. ; Man opløser stoffet, fylder op til stregen og vender kolben.",
        "PIPETTE ; Glasrør til at afmåle og overføre et nøjagtigt rumfang væske. ; En fuldpipette har én streg, en målepipette har en skala.",
        "BURETTE ; Langt glasrør med skala og hane, der bruges ved titrering. ; Man aflæser rumfanget før og efter og trækker fra.",
        "TITRERING ; Metode, hvor man tilsætter en opløsning dråbevis, til en reaktion netop er fuldført. ; Ud fra forbruget beregnes koncentrationen i den ukendte opløsning.",
        "ÆKVIVALENSPUNKT ; Punktet, hvor der er tilsat netop nok til at reagere med alt stoffet. ; Her passer stofmængderne sammen efter reaktionsskemaet. Et farveskift viser det.",
        "INDIKATOR ; Stof, der skifter farve og viser, hvornår en titrering er færdig. ; I syre-base-titreringer bruges fx bromthymolblåt eller phenolphthalein.",
        "MOHRTITRERING ; Metode, hvor chlorid bestemmes med sølvnitrat og chromat som indikator. ; Når alt chlorid er fældet som AgCl, danner næste dråbe rødbrunt Ag₂CrO₄.",
        "STANDARDOPLØSNING ; Opløsning med en kendt, nøjagtig koncentration. ; Den kommer i buretten ved en titrering.",
        "KOLORIMETRISK ; Om en titrering, hvor et farveskift viser slutpunktet. ; Indikatoren skifter farve ved ækvivalenspunktet.",
        "MASSEPROCENT ; Massen af et stof i procent af hele blandingens masse. ; 5 g salt i 100 g opløsning er 5 %.",

        "Område c6: C6 Organisk kemi",
        "ORGANISK KEMI ; Læren om carbonforbindelser. ; Organiske stoffer indeholder næsten altid både carbon og hydrogen.",
        "CARBONHYDRID ; Stof af kun C og H, fx methan. ; Det kaldes også en kulbrinte. Alkaner og alkener er eksempler.",
        "ALKANER ; Mættede carbonhydrider med kun enkeltbindinger, CₙH₂ₙ₊₂. ; Methan, ethan og propan er de første tre.",
        "ALKENER ; Carbonhydrider med mindst én dobbeltbinding mellem to C-atomer. ; Med én dobbeltbinding er formlen CₙH₂ₙ. Ethen er den mindste.",
        "METHAN ; Den mindste alkan, CH₄. ; Methan er hovedbestanddelen af naturgas og en kraftig drivhusgas.",
        "PROPAN ; Alkanen med tre C-atomer, C₃H₈. ; Den bruges som flaskegas til grill og gasbrændere.",
        "BUTAN ; Alkanen med fire C-atomer, C₄H₁₀. ; Den er gassen i lightere og findes som to isomerer.",
        "ISOMERER ; Stoffer med samme molekylformel, men forskellig struktur. ; Butan og 2-methylpropan har begge formlen C₄H₁₀.",
        "ZIGZAGFORMEL ; Tegning, hvor kun C-kæden vises som en knækket streg. ; Hvert knæk og hver ende er et C-atom, og H-atomerne på C tegnes ikke.",
        "HOVEDKÆDE ; Den længste sammenhængende kæde af C-atomer i et molekyle. ; Den giver stammen i navnet: fem C-atomer giver -pentan.",
        "SIDEKÆDE ; Kort kæde, der sidder på den længste kæde, fx methyl. ; I navnet står den foran med et nummer, fx 2-methylbutan.",
        "FORGRENET ; Om en carbonkæde med sidekæder. ; 2-methylpropan er det. Sådanne alkaner koger lavere end ligekædede med samme formel.",
        "METHYL ; Sidekæden -CH₃. ; Navnet kommer af methan. I 2-methylpropan sidder den på C nr. 2.",
        "ETHYL ; Sidekæden -CH₂CH₃. ; Navnet kommer af ethan.",
        "FUNKTIONEL GRUPPE ; Den del af et molekyle, der bestemmer stoffets kemiske egenskaber. ; Fx -OH i alkoholer og -COOH i carboxylsyrer.",
        "ALKOHOLER ; Organiske stoffer med en -OH-gruppe på et C-atom. ; Ethanol, C₂H₅OH, er den i øl og vin.",
        "HYDROXYGRUPPE ; Gruppen -OH på et C-atom. ; Den gør molekylet mere polært og giver hydrogenbindinger.",
        "ETHANOL ; Alkoholen i øl og vin, C₂H₅OH. ; Den blandes med vand i alle forhold, fordi -OH-gruppen danner hydrogenbindinger.",
        "CARBOXYLSYRE ; Organisk syre med gruppen -COOH. ; Eddikesyre, CH₃COOH, er en af dem. De er svage syrer.",
        "FEDTSYRE ; Lang carboxylsyre, der indgår i fedtstoffer. ; Tre af dem bundet til glycerol giver et triglycerid.",
        "GLYCEROL ; Alkohol med tre -OH-grupper, der binder fedtsyrerne i et fedtstof. ; Den hedder også glycerin og er sød og tyktflydende.",
        "TRIGLYCERID ; Fedtstof af glycerol og tre fedtsyrer. ; Bindingerne mellem glycerol og fedtsyrerne er esterbindinger.",
        "ESTERBINDING ; Bindingen mellem glycerol og en fedtsyre i et fedtstof. ; Den dannes, når en -OH og en -COOH går sammen, og der fraspaltes vand.",
        "MÆTTET ; Om en fedtsyre eller et carbonhydrid med kun enkeltbindinger mellem C-atomerne. ; Fedt af den slags er fast ved stuetemperatur, fx smør.",
        "UMÆTTET ; Om et molekyle med mindst én dobbeltbinding mellem to C-atomer. ; Fedtsyrer af den slags har knæk i kæden og giver olier, der er flydende ved stuetemperatur.",
        "HARSK ; Om fedt, der lugter og smager dårligt, fordi det har reageret med luftens oxygen. ; Umættet fedt bliver det lettest, fordi dobbeltbindingerne angribes.",
        "ADDITION ; Reaktion, hvor atomer sættes på en dobbeltbinding, så den bliver til en enkeltbinding. ; Ethen og brom giver 1,2-dibromethan, og bromvandet affarves.",
        "SUBSTITUTION ; Reaktion, hvor et H-atom byttes ud med et andet atom, fx brom. ; Alkaner reagerer med brom i lys på den måde, og der dannes HBr.",

        "Område c7: C7 Syre og base",
        "SYRE ; Stof, der kan afgive en hydron, H⁺. ; Fx HCl, der afgiver H⁺ til vand, så der dannes H₃O⁺ og Cl⁻.",
        "BASE ; Stof, der kan optage en hydron, H⁺. ; Fx OH⁻ og NH₃.",
        "HYDRON ; Andet ord for H⁺: en hydrogenkerne uden elektron. ; I syre-base-reaktioner overføres den fra syren til basen.",
        "OXONIUM ; Ionen H₃O⁺, der dannes, når en syre afgiver H⁺ til vand. ; Jo mere af den, jo lavere pH.",
        "PROTOLYSE ; Reaktion, hvor en hydron overføres fra en syre til en base. ; Fx HCl + H₂O → H₃O⁺ + Cl⁻.",
        "KORRESPONDERENDE ; Om en syre og en base, der kun adskiller sig ved én H⁺, fx HCl og Cl⁻. ; De kaldes et syre-basepar.",
        "STÆRK SYRE ; Et stof, hvor alle molekylerne afgiver deres hydron til vand, fx HCl. ; I 0,10 M HCl er [H₃O⁺] = 0,10 M, og pH er 1,0.",
        "SVAG SYRE ; Et stof, hvor kun en lille del af molekylerne afgiver H⁺ til vand. ; Eddikesyre er en af dem. pH bliver højere end for HCl med samme koncentration.",
        "PH-VÆRDI ; Tal fra ca. 0 til 14, der viser, hvor surt noget er. ; pH = −log[H₃O⁺]. 7 er neutralt ved 25 °C.",
        "SUR ; Om en opløsning med pH under 7. ; Her er der flere H₃O⁺ end OH⁻. Citronsaft og eddike er eksempler.",
        "BASISK ; Om en opløsning med pH over 7. ; Her er der flere OH⁻ end H₃O⁺. Sæbe og natron giver den slags opløsninger.",
        "NEUTRAL ; Hverken sur eller basisk: pH 7 ved 25 °C. ; Her er [H₃O⁺] = [OH⁻].",
        "NEUTRALISATION ; Reaktion mellem en syre og en base, der ophæver hinandens virkning. ; H₃O⁺ + OH⁻ → 2 H₂O.",
        "AUTOPROTOLYSE ; Reaktion, hvor to vandmolekyler selv udveksler en H⁺. ; 2 H₂O ⇌ H₃O⁺ + OH⁻. Den sker i alt vand.",
        "VANDS IONPRODUKT ; [H₃O⁺] · [OH⁻] = 1,0 · 10⁻¹⁴ M² ved 25 °C. ; Derfor gælder pH + pOH = 14.",
        "EDDIKESYRE ; Trivialnavnet for ethansyre, CH₃COOH. ; Den er en svag syre og findes i husholdningseddike.",
        "SALTSYRE ; Opløsning af hydrogenchlorid, HCl, i vand. ; Den er en stærk syre og findes også i mavesaften.",
        "NATRIUMHYDROXID ; NaOH, en stærk base, der også kaldes kaustisk soda. ; I vand giver den Na⁺ og OH⁻.",
        "AMMONIAK ; NH₃, en svag base med skarp lugt. ; Den optager H⁺ og danner ammonium, NH₄⁺.",
        "TITRERKURVE ; Graf over pH mod tilsat rumfang base eller syre. ; Ved ækvivalenspunktet springer pH brat.",
        "ÆTSENDE ; Faremærket på stærke syrer og baser: de ødelægger hud og øjne. ; Brug altid sikkerhedsbriller. Hæld syre i vand, ikke vand i syre.",

        "Område c8: C8 Redox",
        "REDOXREAKTION ; Reaktion, hvor der overføres elektroner fra ét stof til et andet. ; Det ene stof oxideres, og det andet reduceres.",
        "OXIDATION ; Det, der sker med et stof, der afgiver elektroner. ; Oxidationstallet stiger, fx Zn → Zn²⁺ + 2 e⁻.",
        "REDUKTION ; Det, der sker med et stof, der optager elektroner. ; Oxidationstallet falder, fx Cu²⁺ + 2 e⁻ → Cu.",
        "OXIDATIONSTAL ; Regnetal for, hvor mange elektroner et atom har afgivet eller optaget. ; I H₂O har O −II og H +I. Summen i et neutralt stof er 0.",
        "OXIDATIONSMIDDEL ; Stoffet, der optager elektroner og selv bliver reduceret. ; Fx O₂, Cl₂ og MnO₄⁻.",
        "REDUKTIONSMIDDEL ; Stoffet, der afgiver elektroner og selv bliver oxideret. ; Fx uædle metaller som Zn og Fe.",
        "SPÆNDINGSRÆKKEN ; Metallerne ordnet efter, hvor let de afgiver elektroner. ; Et metal kan reducere ionerne af de metaller, der står til højre for det.",
        "UÆDELT METAL ; Grundstof, der let afgiver elektroner og står til venstre i spændingsrækken. ; Natrium, magnesium og zink er eksempler. De reagerer med syre, og der dannes hydrogen.",
        "ÆDELMETAL ; Metal yderst til højre i spændingsrækken, der næsten ikke reagerer. ; Guld, platin og sølv er eksempler.",
        "KALIUMPERMANGANAT ; KMnO₄, et dybviolet salt og et stærkt oxidationsmiddel. ; I sur opløsning reduceres MnO₄⁻ til den næsten farveløse Mn²⁺.",
        "HYDROGENPEROXID ; H₂O₂, også kaldet brintoverilte. ; Det bruges til blegning og som oxidationsmiddel.",
        "RUST ; Det rødbrune stof, der dannes, når jern reagerer med oxygen og vand. ; Det er jernoxider med vand. Jern oxideres fra 0 til +III.",
        "KORROSION ; Når et metal langsomt nedbrydes af stoffer i omgivelserne, fx rust på jern. ; Det er en redoxreaktion, hvor metallet oxideres.",
        "JERN ; Grundstof nr. 26 og det metal, der ruster. ; Det danner både Fe²⁺ og Fe³⁺. Stål er det med lidt carbon.",
        "KOBBER ; Rødligt metal, der bruges i elektriske ledninger. ; Det står til højre for hydrogen i spændingsrækken og opløses derfor ikke i saltsyre.",
        "ZINK ; Uædelt metal, der bruges til at beskytte jern mod rust. ; Det afgiver elektroner lettere end jern og bliver oxideret i stedet."
    ];

    var HISTORIE = [
        "Område industri: Industrialiseringen",
        "INDUSTRIALISERING ; Overgangen fra håndværk og landbrug til produktion med maskiner i fabrikker. ; Den begyndte i England i sidste halvdel af 1700-tallet og bredte sig i 1800-tallet til resten af Europa, USA og Japan.",
        "DAMPMASKINE ; Maskinen, James Watt forbedrede, så fabrikker ikke længere skulle ligge ved en å. ; Watts udgave fra 1769 gjorde fabrikkerne uafhængige af vandkraft, så de kunne placeres frit.",
        "SPINNING JENNY ; Engelsk spindemaskine fra 1760'erne, der kunne spinde mange tråde på én gang. ; James Hargreaves' hånddrevne maskine gjorde spinderiet langt hurtigere.",
        "TEKSTILINDUSTRI ; Den branche, der lavede garn og stof, og som blev mekaniseret først i England. ; Maskiner som Spinning Jenny flyttede produktionen fra hjemmene ind på fabrikkerne.",
        "JERNBANE ; Transport på skinner, der fra 1830 forbandt Liverpool og Manchester. ; Den gjorde transport af varer og mennesker langt hurtigere og billigere.",
        "MANUFAKTUR ; Mellemtrin mellem håndværk og fabrik: mange håndværkere samlet i ét hus. ; Håndværkerne arbejdede stadig med hånden, men med en vis deling af opgaverne.",
        "ARBEJDSDELING ; At dele produktionen op i små, enkle opgaver, som hver person gentager hele dagen. ; Så kunne ufaglærte hurtigt læres op, og der blev produceret mere.",
        "INDHEGNING ; Da englændernes fælles græsningsarealer blev samlet til store, private marker (engelsk: enclosure). ; De større marker gav mere effektivt landbrug, men mange småbønder mistede deres jord og drog til byerne.",
        "GODSEJERE ; Rige jordejere, der også investerede i miner, kanaler og handel. ; I England ejede de en stor del af jorden, og deres overskud var med til at finansiere industrialiseringen.",
        "STÆNDERSAMFUND ; Samfundet før industrialiseringen, hvor gejstlighed og adel havde privilegier. ; Befolkningen var delt i stænder, og ens plads var bestemt af fødslen.",
        "BØRNEARBEJDE ; Det, den danske fabrikslov af 1873 satte aldersgrænser for. ; Loven forbød blandt andet fabriksarbejde for børn under 10 år.",
        "FATTIGKVARTER ; Byernes tætte, usunde boligområder, hvor arbejderne boede. ; Arbejderfamilierne boede tæt sammenpakket med dårlige sanitære forhold og mange sygdomme.",

        "Område ideologier: Ideologier generelt",
        "IDEOLOGI ; Sammenhængende sæt af tanker om, hvordan samfundet bør indrettes. ; Liberalisme, socialisme og konservatisme er de tre klassiske.",
        "VENSTREFLØJEN ; Politisk side, der har navn efter, hvor de revolutionære sad i Frankrigs nationalforsamling i 1789. ; De revolutionære satte sig til venstre for formanden, kongens tilhængere til højre.",
        "HØJREFLØJEN ; Politisk side, der har navn efter, hvor kongens tilhængere sad i nationalforsamlingen i 1789. ; Kongens tilhængere satte sig til højre for formanden, de revolutionære til venstre.",
        "VELFÆRDSSTAT ; Stat, der via skatter sikrer alle borgere uddannelse, sundhed og tryghed. ; I den nordiske model gælder ydelserne alle borgere, ikke kun de fattigste.",

        "Område liberalisme: Liberalisme",
        "LIBERALISME ; Ideologien, der bygger på Adam Smith og det frie marked. ; Staten skal blande sig så lidt som muligt, så den enkeltes frihed og handel kan udfolde sig.",
        "MARKEDSØKONOMI ; System, hvor udbud og efterspørgsel bestemmer priser og produktion, ikke staten. ; Fri konkurrence skal sikre de bedste varer til de laveste priser.",
        "DEN USYNLIGE HÅND ; Adam Smiths billede på, at egeninteresse i et frit marked gavner alle. ; Når hver enkelt søger sin egen fordel, ender det ifølge Smith med at gavne hele samfundet.",
        "MERKANTILISME ; Den ældre økonomiske politik med importtold, som Adam Smith kritiserede. ; Staten skulle beskytte den hjemlige produktion og samle rigdom ved at eksportere mere, end man importerede.",
        "NÆRINGSFRIHED ; Retten til frit at drive erhverv. Vedtaget i Danmark i 1857. ; Den afskaffede laugenes eneret, som mange håndværkere havde ønsket at bevare.",
        "SOCIALLIBERALISME ; John Stuart Mills retning: frihed, men staten skal gribe ind mod fattigdom. ; I modsætning til den klassiske liberalisme skal staten sikre, at alle har mulighed for at bruge deres frihed.",

        "Område socialisme: Socialisme",
        "KAPITALISME ; Økonomisk system, hvor private ejer fabrikker og maskiner og producerer for profit. ; Ifølge Marx bestod det af to modsatte klasser: kapitalisterne og arbejderne.",
        "KLASSEKAMP ; Marx' idé om, at konflikten mellem kapitalister og arbejdere driver historien. ; Marx mente, at kampen til sidst ville ende med en revolution.",
        "PROLETARIAT ; Marx' ord for arbejderklassen. ; Arbejderne ejede kun deres arbejdskraft, som de solgte til kapitalisterne for løn.",
        "BOURGEOISIET ; Marx' ord for borgerskabet, der ejede fabrikkerne. ; De ejede produktionsmidlerne og levede af overskuddet fra arbejdernes arbejde.",
        "PRODUKTIONSMIDLER ; Fabrikker, maskiner og jord: det, man fremstiller varer med. ; Marx mente, at de skulle ejes i fællesskab, ikke af kapitalisterne.",
        "DEN HISTORISKE MATERIALISME ; Marx' teori om, at økonomien er basis og bestemmer samfundets overbygning. ; Samfundets økonomiske grundlag bestemmer ifølge teorien dets love, moral og kultur.",
        "DET KOMMUNISTISKE MANIFEST ; Skrift fra 1848 af Marx og Engels, der slutter: Proletarer i alle lande, foren jer! ; Det opfordrede arbejderne til at gøre revolution mod borgerskabet.",
        "DET KLASSELØSE SAMFUND ; Marx' endemål, hvor ingen ejer mere end andre, og staten er overflødig. ; Produktionsmidlerne skulle ejes af alle, og så var der ikke længere brug for en statsmagt.",
        "REFORMSOCIALISME ; Eduard Bernsteins vej: bedre vilkår for arbejderne gennem demokrati, ikke revolution. ; Forandringerne skulle ske gradvist gennem valg, love og fagforeninger.",
        "FAGFORENING ; Arbejdernes sammenslutning, der kæmper for bedre løn og arbejdstid. ; Efter 1870 organiserede flere og flere arbejdere sig på den måde.",
        "BOLSJEVIKKER ; Lenins fløj af de russiske socialister, der tog magten i 1917. ; Navnet betyder flertallet. De ville have revolution med det samme.",
        "MENSJEVIKKER ; Den moderate fløj af de russiske socialister, som tabte til Lenin. ; Navnet betyder mindretallet. De ville have en langsommere udvikling.",

        "Område konservatisme: Konservatisme",
        "KONSERVATISME ; Ideologien, der vil bevare det, der har vist sig at virke, og kun ændre i små skridt. ; Edmund Burke formulerede den i 1790 som et svar på Den Franske Revolution.",
        "SOCIALT HIERARKI ; Konservatismens idé om, at hver har sin naturlige plads i samfundet. ; Samfundet blev set som en helhed, hvor hver del har sin opgave.",
        "TRADITION ; Skikke og institutioner, der er overleveret fra tidligere generationer. ; Ifølge Burke er samfundet et produkt af sin historie, og forandringer skal respektere det, der virker."
    ];

    NK.Ordlister = [
        { id: "kemi", titel: "Kemi C", tekst: KEMI.join("\n") },
        { id: "historie", titel: "Historie: industrialisering og ideologier", tekst: HISTORIE.join("\n") }
    ];
}());
